name: CI/CD - Build & Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'CI-CD Pipeline using GitHub Actions & Docker**'
  pull_request:
    paths:
      - 'CI-CD Pipeline using GitHub Actions & Docker/**'

permissions:
  contents: read

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: Project-2-CI-CD-GitHubActions-Docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-ci-cd:latest

      - name: Smoke test (pull image)
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-ci-cd:latest
